name: "[Private] Build and Deploy API"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment (dev or prod)'
      artifact_name:
        required: true
        type: string
        description: 'Name of the artifact containing the cdk.out directory'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-api-infra-prereq:
    name: Deploy API Infra Prereq
    uses: ./.github/workflows/_cdk-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      stack-pattern: ${{ format('ecommerce-service-{0}/api-state', inputs.environment) }}
      artifact_name: ${{ inputs.artifact_name }F}

  build-and-publish-api:
    needs: deploy-api-infra-prereq
    name: Build and Publish API
    uses: ./.github/workflows/_app-build-and-publish.yml
    with:
      app_directory: 'api'
      ecs_cluster: 'portfolio-ecommerce-cluster'
      ecs_repository: 'portfolio-ecommerce-service'
      ecs_service: 'portfolio-ecommerce-service'
      environment: ${{ inputs.environment }}

  deploy-api-infra:
    name: Deploy API Infra
    uses: ./.github/workflows/_cdk-deploy.yml
    needs: build-and-publish-api
    with:
      environment: ${{ inputs.environment }}
      stack-pattern: ${{ format('ecommerce-service-{0}/api', inputs.environment) }}
      artifact_name: ${{ inputs.artifact_name }}

  deploy-api:
    name: Deploy API with CodeDeploy
    uses: ./.github/workflows/_codedeploy-deploy.yml
    needs: [build-and-publish-api, deploy-api-infra]
    with:
      environment: ${{ inputs.environment }}
      image_uri: ${{ needs.build-and-publish-api.outputs.image }}
      application_name: 'portfolio-ecommerce-service'
      deployment_group: 'portfolio-ecommerce-service-dg'
      ecs_cluster: 'portfolio-ecommerce-cluster'
      ecs_service: 'portfolio-ecommerce-service'
