name: "[Private] Deploy API Service"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment (dev or prod)'
      ecs_cluster:
        required: true
        type: string
      ecs_service:
        required: true
        type: string
      ecs_repository:
        required: true
        type: string

env:
  AWS_REGION: us-east-1

jobs:
  deploy-ecs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars[format('{0}_PORTFOLIO_GITHUB_ROLE', inputs.environment)] }}
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CDK dependencies
        working-directory: ./infrastructure
        run: |
          npm install
          npm install -g aws-cdk

      - name: Force update ECS service
        env:
          ECS_SERVICE: ${{ inputs.ecs_service }}
          ECS_CLUSTER: ${{ inputs.ecs_cluster }}
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
