name: "[Private] Destroy Infrastructure"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment (dev or prod)'

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy API
    uses: ./.github/workflows/_cdk-destroy.yml
    with:
      environment: ${{ inputs.environment }}
      stack-pattern: 'ecommerce-service-${{ inputs.environment }}/*'
