name: "[Private] Destroy Infrastructure"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment (dev or prod)'

permissions:
  id-token: write
  contents: read

jobs:
  destroy-api:
    name: Destroy API
    uses: ./.github/workflows/_cdk-destroy.yml
    with:
      environment: dev
      stack-pattern: 'portfolio-stage-${{ inputs.environment }}/ecommerce-api'

  destroy-api-prereq:
    name: Destroy API Prereq
    needs: destroy-api
    uses: ./.github/workflows/_cdk-destroy.yml
    with:
      environment: dev
      stack-pattern: 'portfolio-stage-${{ inputs.environment }}/ecommerce-api-prereq'

  destroy-infra:
    name: Destroy Infra
    needs: destroy-api
    uses: ./.github/workflows/_cdk-destroy.yml
    with:
      environment: dev
      stack-pattern: 'portfolio-stage-${{ inputs.environment }}/ecommerce-infra'
