name: Build and Deploy API

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - prod
        description: 'Environment (dev or prod)'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Synthesize
    uses: ./.github/workflows/_cdk-build.yml

  deploy-api-:
    name: Deploy API
    uses: ./.github/workflows/_api-deploy.yml
    needs: build
    with:
      environment: ${{ inputs.environment }}
      artifact_name: ${{ needs.build.outputs.artifact_name }}

