name: Build and Deploy API

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Synthesize
    uses: ./.github/workflows/_cdk-build.yml

  deploy-api-dev:
    name: Deploy API to Development
    uses: ./.github/workflows/_api-deploy.yml
    needs: build
    with:
      environment: dev
      artifact_name: ${{ needs.build.outputs.artifact_name }}

  wait-for-approval:
    name: Wait for Production Approval
    needs: deploy-api-dev
    runs-on: ubuntu-latest
    environment: production-approval
    steps:
      - name: Approval Gate
        run: echo "Deployment to production approved!"

  deploy-api-prod:
    name: Deploy API to Development
    uses: ./.github/workflows/_api-deploy.yml
    needs: [build, wait-for-approval]
    with:
      environment: prod
      artifact_name: ${{ needs.build.outputs.artifact_name }}
