name: Build and Deploy Auth Stack

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/lib/AuthStack.ts'
      - 'infrastructure/lambda/post-auth/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Synthesize
    uses: ./.github/workflows/_cdk-build.yml

  deploy-auth-stack-dev:
    name: Deploy Auth Stack Dev
    uses: ./.github/workflows/_cdk-deploy.yml
    needs: build
    with:
      environment: dev
      stack-pattern: 'portfolio-stage-dev/ecommerce-auth'
      artifact_name: ${{ needs.build.outputs.artifact_name }}

  deploy-auth-lambda-stack-dev:
    name: Deploy Auth Lambda Stack Dev
    uses: ./.github/workflows/_cdk-deploy.yml
    needs: deploy-auth-stack-dev
    with:
      environment: dev
      stack-pattern: 'portfolio-stage-dev/ecommerce-auth-lambda-perms'
      artifact_name: ${{ needs.build.outputs.artifact_name }}

  wait-for-approval:
    name: Wait for Production Approval
    needs: deploy-auth-lambda-stack-dev
    runs-on: ubuntu-latest
    environment: production-approval
    steps:
      - name: Approval Gate
        run: echo "Deployment to production approved!"

  deploy-auth-stack-prod:
    name: Deploy Auth Stack Prod
    uses: ./.github/workflows/_cdk-deploy.yml
    needs: wait-for-approval
    with:
      environment: prod
      stack-pattern: 'portfolio-stage-prod/ecommerce-auth'
      artifact_name: ${{ needs.build.outputs.artifact_name }}

  deploy-auth-lambda-stack-prod:
    name: Deploy Auth Lambda Stack Prod
    uses: ./.github/workflows/_cdk-deploy.yml
    needs: deploy-auth-stack-prod
    with:
      environment: prod
      stack-pattern: 'portfolio-stage-prod/ecommerce-auth-lambda-perms'
      artifact_name: ${{ needs.build.outputs.artifact_name }}
