name: Build and Deploy Auth Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - prod
        description: 'Environment (dev or prod)'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Synthesize
    uses: ./.github/workflows/_cdk-build.yml

  deploy-auth-stack:
    name: Deploy Auth Stack
    uses: ./.github/workflows/_cdk-deploy.yml
    needs: build
    with:
      environment: ${{ inputs.environment }}
      stack-pattern: 'ecommerce-service-${{ inputs.environment }}/auth'
      artifact_name: ${{ needs.build.outputs.artifact_name }}

  deploy-auth-config-stack:
    name: Deploy Auth Configure
    uses: ./.github/workflows/_cdk-deploy.yml
    needs: deploy-auth-stack
    with:
      environment: ${{ inputs.environment }}
      stack-pattern: 'ecommerce-service-${{ inputs.environment }}/auth-config'
      artifact_name: ${{ needs.build.outputs.artifact_name }}
