name: "Destroy Infrastructure"

on:
  workflow_dispatch:
  # This is my portfolio project, so if I forget to manually destroy it, destroy when the day is over
  schedule:
    - cron: '0 6 * * *'

permissions:
  id-token: write
  contents: read

jobs:
  destroy-dev:
    name: Destroy to Development
    uses: ./.github/workflows/_cdk-destroy.yml
    with:
      environment: dev
      stack-pattern: 'ecommerce-infra-dev'

  destroy-prod:
    name: Destroy to Development
    uses: ./.github/workflows/_cdk-destroy.yml
    with:
      environment: prod
      stack-pattern: 'ecommerce-infra-prod'
