name: "Destroy Infrastructure"

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - prod
        description: 'Environment (dev or prod)'

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy
    uses: ./.github/workflows/_infra-destroy.yml
    with:
      environment: ${{ inputs.environment }}
