name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - prod
        description: 'Environment (dev or prod)'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Synthesize
    uses: ./.github/workflows/_cdk-build.yml

  deploy-infra:
    name: Deploy Shared Infra
    needs: build
    uses: ./.github/workflows/_cdk-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      stack-pattern: 'ecommerce-service-${{ inputs.environment }}/infra'
      artifact_name: ${{ needs.build.outputs.artifact_name }}
