name: "Destroy Infrastructure"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy-dev:
    name: Destroy Development
    uses: ./.github/workflows/_infra-destroy.yml
    with:
      environment: dev

  destroy-prod:
    name: Destroy Production
    uses: ./.github/workflows/_infra-destroy.yml
    needs: destroy-dev
    with:
      environment: prod
