name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Synthesize
    uses: ./.github/workflows/_cdk-build.yml

  deploy-infra-dev:
    name: Deploy Shared Infra to Development
    needs: build
    uses: ./.github/workflows/_cdk-deploy.yml
    with:
      environment: dev
      stack-pattern: 'portfolio-stage-dev/ecommerce-infra'
      artifact_name: ${{ needs.build.outputs.artifact_name }}

  wait-for-approval:
    name: Wait for Production Approval
    needs: deploy-infra-dev
    runs-on: ubuntu-latest
    environment: production-approval
    steps:
      - name: Approval Gate
        run: echo "Deployment to production approved!"

  deploy-infra-prod:
    name: Deploy to Production
    needs: [build, wait-for-approval]
    uses: ./.github/workflows/_cdk-deploy.yml
    with:
      environment: prod
      stack-pattern: 'portfolio-stage-prod/ecommerce-infra'
      artifact_name: ${{ needs.build.outputs.artifact_name }}
